-- anche se H2 ha mode=postgres... gli enum non sono gestiti
-- Tipi "enum" modellati con VARCHAR + CHECK
CREATE TABLE onboarding_request (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    requester_user_id BIGINT NOT NULL,
                                    producer_name VARCHAR(255) NOT NULL,
                                    email VARCHAR(255) NOT NULL,
                                    website VARCHAR(1024),
                                    vat_or_fiscal_code VARCHAR(64),
                                    state VARCHAR(32) NOT NULL,
                                    correlation_id VARCHAR(128) NOT NULL,
                                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    CHECK (state IN ('REQUESTED','APPROVED','PREPARATION','ENABLED','FAILED','EXPIRED','REJECTED'))
);

CREATE TABLE onboarding_audit (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  onboarding_id BIGINT NOT NULL,
                                  action VARCHAR(64) NOT NULL,
                                  actor_user_id BIGINT,
                                  ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                  details_json CLOB,
                                  CONSTRAINT fk_onb_audit_req FOREIGN KEY (onboarding_id) REFERENCES onboarding_request(id) ON DELETE CASCADE
);

CREATE TABLE tenant (
                        tenant_id VARCHAR(128) PRIMARY KEY,
                        producer_name VARCHAR(255) NOT NULL,
                        base_dir VARCHAR(1024) NOT NULL,
                        sqlite_path VARCHAR(1024) NOT NULL,
                        state VARCHAR(32) NOT NULL,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CHECK (state IN ('PREPARATION','ENABLED','FAILED','EXPIRED'))
);

CREATE TABLE idempotency_store (
                                   idem_key       VARCHAR(512) PRIMARY KEY,
                                   created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   expires_at   TIMESTAMP
);

CREATE INDEX idx_idem_exp ON idempotency_store(expires_at);

CREATE INDEX idx_onb_req_state ON onboarding_request(state);
CREATE INDEX idx_tenant_state   ON tenant(state);
